### PR TITLE
Add PCPartPicker to the list

### PR DESCRIPTION
**Pull request by ModdedGamers**

### CODE REVIEW

**Comment by Czechball** [comment]
Hello, using "status_code" is much better than "message". PCPartPicker actually returns 404 when you visit a non existent username, so I would suggest changing your PR.

**Comment by ModdedGamers** [comment]
OK. I did that.

**Comment by ModdedGamers** [comment]
Just checked a username. It works!

**Comment by sdushantha** [comment]
@ModdedGamers Thanks for the PR!

I see that you added `.DS_Store` to `.gitignore`, which is great!
Could do us a favour and add a comment, just like the other files in `.gitignore`?
Something like "macOS folder specific metadata information"?

**Comment by ModdedGamers** [comment]
Sure!

**Comment by ModdedGamers** [comment]
Done!

**Comment by sdushantha** [comment]
@ModdedGamers Great! I will merge your PR now 👍

**Pull request merged**
