### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by P3nt3st3r123**
Adding `youtube user` and `youtube channel` search username

### CODE REVIEW

**Comment by P3nt3st3r123** [comment]
image

**Comment by P3nt3st3r123** [comment]
image

**Comment by P3nt3st3r123** [comment]
image

**Comment by sdushantha** [comment]
Could you please send this as a new PR? Seems like you are trying to add some other sites along with YouTube. So a new PR with just YouTube would be appreciated :)

**Pull request closed without merging**
