### PR TITLE
Add separated GitHub actions

### LINKED ISSUE #570: Add a CI verification
Such as Github Actions. If you guys let me, I can send a PR

### PR DESCRIPTION
**Pull request by luchiago**
Add new github action config files

Resolves #570  [Comment](https://github.com/sherlock-project/sherlock/issues/570#issuecomment-630580864)

### CODE REVIEW

**Comment by gorwhh** [comment]
result = gateway.transaction.sale(
  :payment_method_token => "the_token",
  :amount => "10.00"
)

**Comment by gorwhh** [comment]
```
@SebastianElvis 
```

**Comment by luchiago** [comment]
> result = gateway.transaction.sale(
> :payment_method_token => "the_token",
> :amount => "10.00"
> )

@gorwhh what's that?

**Comment by hoadlck** [comment]
Thanks for the update the actions.  It looks great! :)

**Pull request merged**
