### PR TITLE
fix ImportError

### PR DESCRIPTION
**Pull request by cy3erdr4g0n**
error from import other modue in sherlock.py
   
 from .__init__ import ( # noqa: E402
ImportError: attempted relative import with no known parent package

### CODE REVIEW

**Comment by ppfeister** [comment]
Hey @cy3erdr4g0n --- how did you attempt to run Sherlock?

These imports are `sherlock.` rather than relative due to the fact Sherlock is an installable package rather than a script.

**Comment by cy3erdr4g0n** [comment]
Cd sherlock 
Cd sherlock 
Python3 sherlock {username}

**Comment by ppfeister** [comment]
That would be the cause of your errors right there, actually.

Sherlock transitioned from a simple script to a proper installable package some time ago. Take a look at https://sherlockproject.xyz/installation for the up to date methods. You don't need the source code for any of the standard methods found via that link.

Let me know how it goes

**Comment by ppfeister** [comment]
#2213 (staged for 0.15.0) will warn users when ran with the old unsupported method -- closing.

**Pull request closed without merging**
