### PR TITLE
Removed BitCoinForum

### PR DESCRIPTION
**Pull request by KwiatekMiki**
bitcoinforum.com was probably discontinued or something like that because even on the main website I will get a 404 error so that's why I'm removing it.

### CODE REVIEW

**Comment by ppfeister** [comment]
I noticed the same error when opening #2068 

Instead of removing it however, I added a second test for the 404 so it can function normally if it comes back online. Were you able to find anything saying whether or not they'll be returning? They seemed pretty active on the last wayback scrape. I came up pretty dry on my end and figured I'd play it safe

**Comment by KwiatekMiki** [comment]
> Were you able to find anything saying whether or not they'll be returning?

**Comment by KwiatekMiki** [comment]
> Were you able to find anything saying whether or not they'll be returning?

no.

**Comment by ppfeister** [comment]
Oh well.
I was really hoping for something definitive but what can ya do 🤷‍♂️

**Comment by sdushantha** [comment]
fixed in #2068

**Pull request closed without merging**
