### PR TITLE
Adds support for Aidungeon.io

### PR DESCRIPTION
**Pull request by arrudagates**
I just found this project and I wanted to try adding a website, I tested and it's working fine.

### CODE REVIEW

**Comment by arrudagates** [comment]
Ok so apparently i missed the username doesn't exist check, i'll fix that

**Comment by arrudagates** [comment]
I'm not sure why this is failing, I have compared to other pull requests that merged, and they seem to do the same thing, I guess it could be because there's a quick loading screen before the profile or the message appears.

**Comment by darvell** [comment]
Merge from master and run the site generator markdown script.

The site generation script should really be done as a post-PR merge thing with GitHub workflows...

**Comment by arrudagates** [comment]
done

**Pull request closed without merging**
