### PR TITLE
Remove fixed value of "username_unclaimed" #1628

### PR DESCRIPTION
**Pull request by DenavDot**
I couldn't change [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md) because removing the variable was much more difficult with the text in-between.

### CODE REVIEW

**Comment by sdushantha** [comment]
This a very smart solution! I'll need double check this and will get back to you as soon as possible. 
Could I ask why you decided to use the value 32 for the length? Nothing wrong in doing so, I'm just curious :)

**Comment by DenavDot** [comment]
The value isn't all that important; though it had to be long enough to avoid any conflicts with an actual username
I was told [here](https://github.com/sherlock-project/sherlock/issues/1628) the value 32 would be ideal!

**Comment by rf-peixoto** [comment]
> The value isn't all that important; though it had to be long enough to avoid any conflicts with an actual username I was told [here](https://github.com/sherlock-project/sherlock/issues/1628) the value 32 would be ideal!

I suggested the value 32 exactly because of the size. It's big enough to guarantee a unique username and small enough to have a negligible impact on performance. Probably 24 would be enough. But 32 prevents the value from having to be increased in the very near future. :)

**Comment by sdushantha** [comment]
I unfortunately forgot about this issue, sorry about that. Could you fix the merge conflicts and ping me? I'll merge this PR right away once its fixed :+1:

**Comment by DenavDot** [comment]
@sdushantha all good! conflicts are fine now

**Comment by sdushantha** [comment]
Ah, this breaks the tests. Would be able to fix this up?

**Comment by DenavDot** [comment]
This should do it. @sdushantha

**Comment by sdushantha** [comment]
@DenavDot I think something broke :/

**Comment by DenavDot** [comment]
Ouch, what happened?

**Comment by DenavDot** [comment]
@sdushantha 
I checked the error:
```python
 SiteInformation(site_name,
                                site_data[site_name]["urlMain"],
                                site_data[site_name]["url"],
                                site_data[site_name]["username_claimed"],
                                site_data[site_name]["username_unclaimed"],
                                site_data[site_name],
                                site_data[site_name].get("isNSFW",False)
                                    )
```
 my bad! seems like removing the `username_unclaimed` key should resolve the issue, since right now its looking for a nonexistent value inside the file. Let me know if there's anything else

**Comment by sdushantha** [comment]
I fixed it in the latest commit, so no worries :)

**Comment by DenavDot** [comment]
phew! good to hear 😄

**Comment by rf-peixoto** [comment]
Thank you, guys! <3

**Comment by charlieley** [comment]
I took the latest commit, but when I try and do a basic username search, all get is an error saying 
`Missing attribute 'username_unclaimed'`. Command is 
`python sherlock <some_user>`
Used to work fine before, am I missing something?

**Pull request merged**
