### PR TITLE
Rename importable module

### PR DESCRIPTION
**Pull request by ppfeister**
Importable module name collides with that of another package on PyPI, causing issues downstream. This PR introduces parity between the standard package name and the module name, avoiding this collision, and meeting conventions.

In particular, this addresses blocking conflicts discussed in Debian #1071007 and #1072733.

This may be a breaking change for some end users, so it may be worth bumping the minor or patch number.

### CODE REVIEW

**Comment by ppfeister** [comment]
Tests are PASSING --- disregard errors.

Validation against remote schema fails before merge due to the file path change. This is expected.

Review changes but do not merge into master.

**Comment by ppfeister** [comment]
Installable package remains `sherlock-project`. Importable module switched from `sherlock` to `sherlock_project`, with directory rename. Binary entry point remains `sherlock`.

**Comment by ppfeister** [comment]
Staged [staging/0.15.0rc0](https://github.com/sherlock-project/sherlock/tree/staging/0.15.0rc0)

**Review by sdushantha — APPROVED** [review]
There is a conflict in the data.json in <https://github.com/sherlock-project/sherlock/pull/2190>
But thats due to the rename of the dir `sherlock` --> `sherlock_project`

**Comment by ppfeister** [comment]
@sdushantha conflict here is resolved in rc1, so it can be ignored. I'll be ff-ing master to rc1 once ready.

**Comment by alparslan1453927** [comment]
ca781a3c3be60d244a524b8dd5c8dc3460631ceb

**Pull request merged**
