### PR TITLE
Added hashnode

### PR DESCRIPTION
**Pull request by codewithpom**

### CODE REVIEW

**Comment by codewithpom** [comment]
Added hashnode as a supported site

**Comment by sdushantha** [comment]
I see that a GitPod related file was added. Since that file has nothing to do with this PR, please remove it. I will then consider merging this PR

**Comment by codewithpom** [comment]
Yup 
Deleted

**Review by sdushantha — APPROVED** [review]
Thank you, looks good now 👍

**Comment by codewithpom** [comment]
Can you please add the hacktoberfest-accepted label

**Comment by sdushantha** [comment]
Sorry, forgot about that. I've dont it now :)

**Comment by codewithpom** [comment]
Thanks

**Pull request merged**
