### PR TITLE
Build Workflow Action

### PR DESCRIPTION
**Pull request by MoeDevelops**
Since someone complained about the lack of an executable file I have added a GitHub Workflow, that automatically builds the source code using PyInstaller.
Because of the way the project is set up the script has to remove the __init__.py file during building, so that PyInstaller works properly.

The person that complained: https://www.reddit.com/r/github/comments/1at9br4/i_am_new_to_github_and_i_have_lots_to_say/

### CODE REVIEW

**Comment by MoeDevelops** [comment]
If you want to test the builds you can download them from my forks action
https://github.com/MoeDevelops/sherlock/actions/runs/7964054906

I have tested Linux and Windows via wine

**Review by Chizaruu — APPROVED** [review]
Lovely.

**Comment by wineTGH** [comment]
I don't think that every commit on the master branch should start a new build process. More logically to make a release branch and watch for commits here.

But this needs actions from maintainers or creator of this project

**Review by matheusfelipeog — COMMENTED** [review]
See https://github.com/sherlock-project/sherlock/issues/2006#issuecomment-1981592479

**Pull request closed without merging**
