### PR TITLE
added freecodecamp website

### PR DESCRIPTION
**Pull request by naveennamani**
added https://www.freecodecamp.org website and run site_list.py

### CODE REVIEW

**Comment by naveennamani** [comment]
@sdushantha can you please check if there is any problem with this PR. It already has passed all the checks as I contributed to this repo earlier also.
Thanks

**Comment by sdushantha** [comment]
I'll try merging but I'm just a little unsure if there will be any issues as you are removing Google Developer in this commit. But it has already been removed from this repo a while ago

**Comment by sdushantha** [comment]
image

🥳

**Comment by naveennamani** [comment]
When you removed Google developer after I made this PR, it showed merge conflicts, so to balance that I've also removed it.

**Pull request merged**
