### PR TITLE
Adding support for exophase via `data.json` for #2248

### PR DESCRIPTION
**Pull request by gtkacz**

### CODE REVIEW

**Comment by gtkacz** [comment]
Hey @ppfeister this is an implementation of #2248, it's only in draft because when trying to run `poetry run sherlock --site exophase --local testuser` I'm getting a Pandas error: `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by nktkhndlwl** [comment]
@gtkacz were you able to fix the pandas error? i'm getting that too

**Comment by Nuung** [comment]
@gtkacz @nktkhndlwl Are you using Python 3.10 or higher? If so, you can try running the following command: pip install numpy@^1.21 pandas or poetry add numpy@^1.21 pandas.

(Please make sure to reinitialize your virtual environment before running the commands.)"

**Review by ppfeister — APPROVED** [review]
LGTM. Appreciate the add guys. Merging.

@gtkacz @nktkhndlwl This will close once merged but drop a new reply and ping me if you're still encountering the pandas issue. Otherwise GTG

**Pull request merged**
