### PR TITLE
Directory Structure For Sherlock Restructure

### PR DESCRIPTION
**Pull request by hoadlck**
Do Not Merge! :)

At this point, I have only moved the existing files around so that they align with the future directory structure.  I have not even started with the more significant restructure of the code itself.

But, I figured I would push the branch up so everyone could see what I am thinking about.

### CODE REVIEW

**Comment by hoadlck** [comment]
I added some [Restructure-Notes](https://github.com/sherlock-project/sherlock/wiki/Restructure-Notes) to the Wiki.  Feel free to add to it.

**Comment by TheYahya** [comment]
So far look good to me, It's a great job @hoadlck 👍

**Comment by kittehh204** [comment]
??? It makes me sick to my stomach but I have to learn...

**Comment by hoadlck** [comment]
The latest development for this is included in #590.  So, this can be closed out.

**Pull request closed without merging**
