### PR TITLE
fixed speedrun site support #2288

### PR DESCRIPTION
**Pull request by Suramyavns**

### CODE REVIEW

**Comment by ppfeister** [comment]
This PR seems to duplicate Speedrun, and with two different detection methods. Safe to say that this is unintentional?

PS - The addition of username_unclaimed is going to make this fail schema validation.

**Comment by Suramyavns** [comment]
I removed the duplication of speedrun and fixed the error checking in the existing site data for speedrun

**Comment by Suramyavns** [comment]
hey this is one of my first FOSS contributions I just wanted to know if this means that my code is accepted because I don't see a merge with the main branch for sherlock project

**Comment by ppfeister** [comment]
Busy week is all. Schema wise it's good now, I've just gotta validate the check when I have a moment. Won't be long though as long as it checks out :+1:

**Comment by Suramyavns** [comment]
> Busy week is all. Schema wise it's good now, I've just gotta validate the check when I have a moment. Won't be long though as long as it checks out 👍

hey merge it now maybe?

**Comment by YuvamGupta** [comment]
@ppfeister please merge it now

**Review by ppfeister — APPROVED** [review]
LGTM! Appreciate the fix and the conversion back to status_code (more consistent across regions)
Merging into master

**Pull request merged**
