### PR TITLE
Add support for TikTok

### PR DESCRIPTION
**Pull request by deceitfulvision**
Fully tested and working

### CODE REVIEW

**Comment by mehtaarn000** [comment]
Just a question. If U.S president Donald Trump bans TikTok in the United States, what would happen to the U.S accounts? And if this pull request is merged, would something go wrong?

**Comment by deceitfulvision** [comment]
If things continue as they are going now, Oracle will be operating TikTok in the US so it should continue to work. It may need to updated once Oracle has fully implemented whatever kind of system they plan to put in place.

**Comment by sdushantha** [comment]
@deceitfulvision Since we had removed TikTok in the past because of false positive issues, could you please remove TikTok from the `removed_sites.md` and `removed_sites.json` as it seems to be  working again?

**Comment by deceitfulvision** [comment]
Sure thing, I can do it once I'm home.

**Comment by deceitfulvision** [comment]
I believe I may have found one or two other site in removed sites that are now working so I might be making another pull request soon.

**Comment by deceitfulvision** [comment]
Done!

**Pull request merged**
