### PR TITLE
Add support for Quizlet and Atom Discussions

### PR DESCRIPTION
**Pull request by mehtaarn000**

### CODE REVIEW

**Comment by mehtaarn000** [comment]
I accidentally deleted the branch from the first pull request, so I made a new one.

**Comment by sdushantha** [comment]
@mehtaarn000 Seems like there is a conflict because of the other PRs I merged earlier. I'll review the PR once the conflicts have been resolved.

**Comment by mehtaarn000** [comment]
Ok, great.

**Review by lostnco1 — APPROVED** [review]

**Comment by sdushantha** [comment]
Closing this. See #850

**Review by lostnco1 — APPROVED** [review]
Where can I submit for a pr

**Comment by sdushantha** [comment]
@lostnco1 try reading this: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

It has a good overview on how pull requests work on GitHub

**Comment by lostnco1** [comment]
@sdushantha Thanks sorry for the late response im just now seeing this

**Pull request closed without merging**
