### PR TITLE
fix false-positive detection on chess.com

### PR DESCRIPTION
**Pull request by josephazrak**

### CODE REVIEW

**Comment by j-dogcoder** [comment]
Someone should merge this! I keep getting false positives

**Comment by AhmedShela** [comment]
someone should merge this

**Comment by j-dogcoder** [comment]
@sdushantha

**Comment by Natan515** [comment]
It doesn't fix it...

**Comment by creekorful** [comment]
See my PR for a fix: https://github.com/sherlock-project/sherlock/pull/1260

**Comment by sdushantha** [comment]
Closing this because it has been fixed in #1260

**Pull request closed without merging**
