### PR TITLE
Fixed Twitter false positive error

### PR DESCRIPTION
**Pull request by billyb2**
Simply changed the url from twitter.com to mobile.twitter.com, as the desktop site will return a 200 error regardless of whether the user exists or not. I ran sites_list.py and also checked for any issues with the script now, and it works now.

### CODE REVIEW

**Comment by sdushantha** [comment]
Hey @billyb2, thank you for fixing that bug! Would you be so kind and undo the edits that you did with `sites_list.py`? After you ran that script it put all the rankings to 0. This is a known problem and has been addressed in #610 
Other than that, everything looks good 👍

**Comment by billyb2** [comment]
Just fixed the ranks. Also, would you mind if I take pull requests that never fixed their merge issues, and just fix them myself?

**Comment by sdushantha** [comment]
> Also, would you mind if I take pull requests that never fixed their merge issues, and just fix them myself?

I dont mind at all, and that would be great help!

**Comment by billyb2** [comment]
Sweet, thanks!

**Pull request merged**
