### PR TITLE
Added LinkedIn.com 

### PR DESCRIPTION
**Pull request by Alexandros-Kordatzakis**
Fully tested and working Linkedin user search.

### CODE REVIEW

**Comment by Alexandros-Kordatzakis** [comment]
I’m sorry, I just realized that I didn’t put **Linkedin** in the correct alphabetical order... I will edit it on Sunday, if you can review it and approve it until then.  I’ll update the file on Sunday.

**Comment by Alexandros-Kordatzakis** [comment]
Updated file with Alphabetical Order. The 3rd one, created in 19-Aug-2019. 

Thank you.

**Comment by LameLemon** [comment]
Tagging the issue too so it's easier to keep track of and closer after merging.
#289

**Comment by Alexandros-Kordatzakis** [comment]
> Tagging the issue too so it's easier to keep track of and closer after merging.
> #289

Thank you!

**Comment by hoadlck** [comment]
There are many conflicts in this PR.  It looks like it has the alphabetization change, even though that is not needed (as the site update script takes care of that).

Can you make a new pull request off of the leading edge of development?

**Comment by Alexandros-Kordatzakis** [comment]
Sure thing!

**Pull request closed without merging**
