### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by zero77**
Add signal community

### CODE REVIEW

**Comment by hoadlck** [comment]
What is this WhiteSource addition about?  I see there page on [how it works](https://www.whitesourcesoftware.com/how-does-it-work/), but I have not dug into registration and whatnot. I assume that the owner of the content needs to create an account? 

Their [Terms And Conditions](https://www.whitesourcesoftware.com/contact-us-open-source/) say that we need to put a link to them somewhere in our project.  So...free advertising?

I think that WhiteSource would be better in a separate PR.  But, I will merge the Signal site addition.

**Comment by zero77** [comment]
@hoadlck 
I have no idea what it is and i don't remember installing or enabling it but, i have just found and removed it.
It looks like its for finding vulnerabilities in code.
https://github.com/marketplace/whitesource-bolt

**Comment by hoadlck** [comment]
Wow! Some app automatically added a commit to your PR?  That is scary.  Did it happen on your local machine, or did it happen after you created your PR?

**Comment by zero77** [comment]
No web ui only and i not sure i will look into it.

**Comment by hoadlck** [comment]
I merged the earlier commit before the WhiteSource change was made.  But, the Signal site is now included.

**Pull request closed without merging**
