### PR TITLE
Fix Invalid usernames for number of pages

### PR DESCRIPTION
**Pull request by mikebgrep**
With this PR, I add ``regexCheck`` value in ``data.json`` file that will check for valid username in the web pages  related to this issue https://github.com/sherlock-project/sherlock/issues/2313.
Its minimize the chance to return a result for a invalid username as the rules  for username from the pages is considered also

### CODE REVIEW

**Review by ppfeister — APPROVED** [review]
Very well done. Thanks for figuring out the patterns for each site
LGTM. Merging into master.

**Comment by ppfeister** [comment]
Changed reverted.

Upon further review, some patterns seem to be incorrect, even if the absurdly long usernames are dealt with. For instance, Discord allows periods, HackTheBox allows up to 32 chars, etc. Corrections are welcome if desired.

Should also note that when within length, F+s are still present.

**Comment by tdfz4kn5v2-png** [comment]
>  It's good to know that these patterns didn't work.Well done for reverting it.
> Regards

What did I do wrong? What user name? Instagram:/lessieh4
Facebook://lessie-ann heerah
Snapchat:// Lessie heerah 
X:// lessieh3
SMS:// 5613465338
iCloud://lessie_poops@msn.com
Google :// lessieh321@gmail.com


All these are not fake!

**Comment by tdfz4kn5v2-png** [comment]
And WhatsApp:// Lessie heerah/561-346-5338
LinkedIn://https://www.linkedin.com/in/lessie-heerah-2440a7186image

That's me. And I can't get into anything the person that found my phone locked me out, and if I keep pushing 2 apps told me my name or images come up on a account that would be banned as well. I just want my photos of my kids my memories. Contacts . Messages and conversations. 3 of them conversations with my dad, and 2 cousins that have passed away from a car accident going off a cliff where I'm from in Trinidad

**Pull request merged**
