### PR TITLE
Fixing False Positives + Few extras

### PR DESCRIPTION
**Pull request by prithvi2k2**
#1071 can be closed now, only if this PR is merged

LiveLeak is shut down!
The site now redirects to a different site called itemfix.com
https://www.theverge.com/2021/5/7/22424356/liveleak-shock-site-shuts-down-itemfix

### CODE REVIEW

**Comment by prithvi2k2** [comment]
@hoadlck , @contributorpw and other contributors Please review the PR and make changes if required, Also close #1071 after successful merge.

**Comment by prithvi2k2** [comment]
https://github.com/sherlock-project/sherlock/pull/1098/commits/9d77aa3efd3d2370cc5fc67f5e5fc687d2a645be improves readability and unexpected behaviour.
Please Refer #80 for more details about the behaviour.

**Comment by prithvi2k2** [comment]
Unexpected behaviour of BabyblogRU, I'm unable to fix BabyBlogRU. Contributors, Help is massively appreciated!!

**Comment by Natan515** [comment]
@prithvi2k2 Can I help you with this project? I mean I will add more websites and try to fix more false positives and code a bit. Will you be active and planning to do more changes to this project?

**Comment by prithvi2k2** [comment]
@Natan515 Surely, I have exams next week, but I can manage 👍

**Comment by prithvi2k2** [comment]
@hoadlck What is the actual purpose of using errorType:"error_msg" type errors, how do they help in user lookup, considering the fact sherlock doesn't web scrape.

**Comment by hoadlck** [comment]
You can see a description of the error message detection method [here](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock#error-message).

>This is the least reliable detection method. In this detection method, Sherlock does a request of the specific site URL which should exist if the desired username has been taken. If the username is unclaimed, then the site does not return any discernible HTTP Status code. Sites with this design will display some error message, or perhaps directly offer the user a chance to sign-up for the site.
>
>For this detection method, Sherlock looks for specific error text. Since the error message might change with minor updates on the site, this mechanism is the most fragile.

**Comment by prithvi2k2** [comment]
> You can see a description of the error message detection method [here](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock#error-message).
> 
> > This is the least reliable detection method. In this detection method, Sherlock does a request of the specific site URL which should exist if the desired username has been taken. If the username is unclaimed, then the site does not return any discernible HTTP Status code. Sites with this design will display some error message, or perhaps directly offer the user a chance to sign-up for the site.
> > For this detection method, Sherlock looks for specific error text. Since the error message might change with minor updates on the site, this mechanism is the most fragile.

Yeah, it's so fragile, returning false positive or negative

**Comment by prithvi2k2** [comment]
Using something like `200<=r.status_code<300` can be used to reduce a detection algorithm, then we don't need `response_url` detection algorithm, I am new to development, do correct me if I am wrong. Also, do check the **second commit in this PR** regarding the same.

**Comment by prithvi2k2** [comment]
I will open a new PR with proper fixes, ignore this.

**Comment by Natan515** [comment]
@prithvi2k2  Let me know in discord :3

**Pull request closed without merging**
