### PR TITLE
Added support for ICQ

### PR DESCRIPTION
**Pull request by d4rkc0nd0r**
Added [ICQ](https://icq.com/) to sites.

### CODE REVIEW

**Comment by sdushantha** [comment]
@d4rkc0nd0r The `username_claimed` that you have set for this site does not exist on the website. Please correct that.

**Comment by d4rkc0nd0r** [comment]
@sdushantha I'll do that for sure.

**Review by d4rkc0nd0r — COMMENTED** [review]
@sdushantha Please review this, I've changed the `username_claimed` and its supporting now.

**Review by sdushantha — APPROVED** [review]

**Comment by sdushantha** [comment]
Thanks, everything looks good 👍

**Comment by d4rkc0nd0r** [comment]
Please do add this site to `sites.md`.

**Comment by sdushantha** [comment]
> Please do add this site to `sites.md`

Done #847

**Comment by d4rkc0nd0r** [comment]
Thank You so much

**Pull request merged**
