### PR TITLE
Reduce false positives (those not caused by WAFs or bot detection)

### LINKED ISSUE #904: Jeuxvideo.com
## Checklist

- [x ] I'm reporting a website that is returning **false positive** results
- [x ] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a seperate issue for each site)

## Description

WRITE DESCRIPTION HERE
http://www.jeuxvideo.com/profil/chaosjesus?mode=infos

I ran the script often this night and this site was very often false Positive

### LINKED ISSUE #1878: Fiverr false positive
## Checklist

- [ x] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a separate issue for each site)

## Description

https://www.fiverr.com/fincali1979 is not a real fiverr account I checked for closed issues and fiverr is marked as fixed, but it doesn't work now

### LINKED ISSUE #1966: Genius.com returns false positive when dot is used
## Checklist

- [ X ] I'm reporting a website that is returning **false positive** results
- [ X ] I've checked for similar site support requests including closed ones
- [ X ] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a separate issue for each site)

## Description

Example: python sherlock julia.cat

Username julia.cat on Genius.com does not return Genius.com/julia.cat, but Genius.com/julia. It removes all letters after dot.

### LINKED ISSUE #1999: Some sites always appear with the username I entered even though it doesn't exist
sites like: RocketTube,  CGTrader,  xHamster, Fiverr,  Modelhub. are always repeated in all the usernames I enter

### LINKED ISSUE #2027: cgtrader is returning false positives
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description
cgtrader is returning a false positive on all usernames.

I believe the issue is that the data.json file identifies it as a errortype: Message but the current website has changed to return a 404 error instead.

On further testing, I found that even when I changed it to an errortype: message to try to address the false positives, it continues to have the same issue. From some of the data I see in Burpsuite, it seems like cgtrader may have cloudflare protection. If someone knows how to verify and confirm this then I suggest we remove cgtrader from the list of sites.

### LINKED ISSUE #2071: Yandex Music has a captcha
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Here's a random username that can't possibly exist: [ecfhlmiuewfimcuhem](https://music.yandex/users/ecfhlmiuewfimcuhem/playlists).

Here's the username from [data.json](https://github.com/sherlock-project/sherlock/blob/master/sherlock/resources/data.json#L2214): [ya.playlist](https://music.yandex/users/ya.playlist/playlists)

When I visit either, I get a captcha (note: JS is disabled in my browser):
image

Unless Sherlock uses Selenium/Pyppeteer, which i highly doubt (it's not in requirements.txt), this captcha isn't really avoidable (I think). Maybe it even shows up with JS enabled, which I didn't check.

I'm not opening a PR removing YandexMusic because it could be an issue that only happens for me, or maybe it's possible to bypass this captcha.

### PR DESCRIPTION
**Pull request by ppfeister**
**The following targets were fixed or partially fixed:**
Archive[.]org (eh. sometimes. it has a loading problem that causes other F+s... some were fixed)
Archive of Our Own
CGTrader
CNET
Contently
Eintracht Frankfurt Forum
GeeksForGeeks
Genius[.]com Artists
Genius[.]com Users
Gumroad
HackerNews
HackerRank
IFTTT
Kongregate
Linktree
OpenStreetMap
Pinkbike
Polymart (often hits bot detection, but can be bypassed with some proxies)
Slides
Splits[.]io
Strava
Telegram
xHamster
YandexMusic
eintracht
jeuxvideo

**The following targets were removed:**
BitcoinForum (likely defunct)
G2G
HexRPG (auth wall)
Metacritic
ModelHub (defunct)
Oracle Communities (auth wall)

**Misc changes:**
Default User Agent updated

___

ModelHub was not added to ./removed_sites.[md|json] as the platform itself is confirmed to be shutting down (and will therefore never return to Sherlock). The other removed targets were documented normally.

Fiverr, Euw, NationStates Nations, NationStates Regions, and a couple others remain occasionally problematic as they are behind WAFs and bot detection services. These WAF-induced false positives are resolved with sister PR #2069 and have partial support for a decent proxy being discussed in #2081.

___

**Issues:**
Fixes #904 
Fixes #1966 
Fixes #1999 (with sister PR #2069)
Fixes #2027 (with sister PR #2069)
Fixes #2071 

**Collateral (trumped or negated):**
Closes #1843 // Removes jeuxvideo instead of applying a fix (a fix is being applied here).
Closes #2083 // Removes ModelHub, which is an action taken here. Would be negated by merge.
Closes #2096 // Fixes Archive[.]org, which is an action taken here. Would be negated by merge.

### CODE REVIEW

**Comment by ppfeister** [comment]
As indicated in #1878, Fiverr is behind Cloudflare. This can lead to inconsistent returns (especially as you make more frequent queries and look more _botty_).

At least on my end, that platform will now at least be hidden when Cloudflare causes delays just the same as if no username is found, while still appearing when Cloudflare _doesn't_ get in the way and a username exists. __Please confirm that you get the same result__.

Euw and both of the NationStates appear to also be behind Cloudflare, although they were a bit more *difficult* to work with. I've just left them. Would you guys be open to a `cloudflare` flag (default false) that when set true uses something like [cloudscraper](https://github.com/VeNoMouS/cloudscraper) instead of standard `requests`? Curious if it's worth exploring.

**Comment by ppfeister** [comment]
A lil bit larger of a pr than first expected........

I think that's all of em, though... Well, I hope that's all of em
When combined with #2069, I'm no longer experiencing any false positives in my results. I'm sure there's some username combo that causes one, but none that I've stumbled upon

For general testing purposes, [ppfeister:rc/combopoc](https://github.com/ppfeister/sherlock/tree/rc/combopoc) currently reflects master with this, #2069, and #2070 all merged.

Cheers.

**Comment by ppfeister** [comment]
Do not merge just yet.
Minor bug discovered with status code validation. Will remediate shortly and update here.

**Comment by ppfeister** [comment]
Bug fixed. Able to be merged again.
Bit more elegant of a solution than the bugged version anyways

**Comment by sdushantha** [comment]
Thank you so much @ppfeister for fixing all of this, I really appriciate it!

**Pull request merged**
