### PR TITLE
Only execute GitHub action when needed

### LINKED ISSUE #2158: Only run GitHub action if it is actually needed
### Description

In #2157, no change was made to the code but the GitHub Action was still executed. This is unnecessary as only the docs were modified. Therefore the Github Action should be modified so that it only gets executed upon code modification

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sdushantha**
fixes #2158

### CODE REVIEW

**Comment by sdushantha** [comment]
Seems like it works
image

**Comment by ppfeister** [comment]
Thinking we should include **/*.ini and **/*.toml as well, since config file changes could impact builds as well

Currently this would include the pyproject, tox, and pytest confs

**Comment by sdushantha** [comment]
@ppfeister I have now added those files

**Review by ppfeister — APPROVED** [review]
LGTM

**Pull request merged**
