### PR TITLE
Added PCPartPicker

### PR DESCRIPTION
**Pull request by DottaPaperella**
Connecting from my location (Italy) it works.
I tried using a VPN but it failed because it needs before to verify that the connection is legit and that is not made by a bot.
I cannot verify if this behaviour is due to the fact that i'm using a VPN or that the website sees that the connection come from the USA.

### CODE REVIEW

**Comment by w3Abhishek** [comment]
It won't work due to CloudFlare proxy. Please close your PR. Have you even tried running the tests before submitting the PR.

**Comment by DottaPaperella** [comment]
> It won't work due to CloudFlare proxy. Please close your PR. Have you even tried running the tests before submitting the PR.

Of course i test it before submitting the pr and it worked. Here's the output of the script executed passing as arguments an existing username ("blue") and a not existing one ("notexistingusername")

```
python3 sherlock.py --json ./resources/data.json --site PCPartPicker blue notexistingusername
[*] Checking username blue on:

[+] PCPartPicker: https://pcpartpicker.com/user/blue/topics

[*] Checking username notexistingusername on:


[*] Results: 1
```

**Comment by w3Abhishek** [comment]
> > It won't work due to CloudFlare proxy. Please close your PR. Have you even tried running the tests before submitting the PR.
> 
> Of course i test it before submitting the pr and it worked. Here's the output of the script executed passing as arguments an existing username ("blue") and a not existing one ("notexistingusername")
> 
> ```
> python3 sherlock.py --json ./resources/data.json --site PCPartPicker blue notexistingusername
> [*] Checking username blue on:
> 
> [+] PCPartPicker: https://pcpartpicker.com/user/blue/topics
> 
> [*] Checking username notexistingusername on:
> 
> 
> [*] Results: 1
> ```

Screenshot_20221006-164536_Termux

I tried curl on the URL you shared above. It return CloudFlare proxy page. It is definitely not going to work for most of the people. 

Here's one [similar case](https://github.com/sherlock-project/sherlock/issues/961#issuecomment-869138050) .

**Comment by DottaPaperella** [comment]
> > > It won't work due to CloudFlare proxy. Please close your PR. Have you even tried running the tests before submitting the PR.
> > 
> > 
> > Of course i test it before submitting the pr and it worked. Here's the output of the script executed passing as arguments an existing username ("blue") and a not existing one ("notexistingusername")
> > ```
> > python3 sherlock.py --json ./resources/data.json --site PCPartPicker blue notexistingusername
> > [*] Checking username blue on:
> > 
> > [+] PCPartPicker: https://pcpartpicker.com/user/blue/topics
> > 
> > [*] Checking username notexistingusername on:
> > 
> > 
> > [*] Results: 1
> > ```
> 
> Screenshot_20221006-164536_Termux
> 
> I tried curl on the URL you shared above. It return CloudFlare proxy page. It is definitely not going to work for most of the people.
> 
> Here's one [similar case](https://github.com/sherlock-project/sherlock/issues/961#issuecomment-869138050) .

What's your output if you use sherlock.py instead of curl?

**Comment by w3Abhishek** [comment]
> 

It gives me the 403 status code. When you send get request, it responds with the CloudFlare proxy page not the actual website. The websites using CloudFlare proxy doesn't work with Sherlock in my experience.

**Pull request closed without merging**
