### PR TITLE
changed dis.cool to tracr.co

### PR DESCRIPTION
**Pull request by apap04**
domain name change, see #561

### CODE REVIEW

**Comment by apap04** [comment]
found out that sites were sorted alphabetically, making changes tomorrow :pp

**Comment by apap04** [comment]
ready to push :)

**Comment by jeroen7s** [comment]
I'm constantly getting false positives for this service.

**Comment by sdushantha** [comment]
@jeroen7s That is because they only allow usernames with max length 32 chars
Here are the criteria for the usernames:
Screenshot 2020-03-11 at 19 49 03 1
Screenshot_2020-03-11 register

**Comment by sdushantha** [comment]
Merging this now 🚀 
Thank you @apap04 for the PR and thank you @jeroen7s for noticing the bug with the long strings :)

**Pull request merged**
