### PR TITLE
Fix false positives

### LINKED ISSUE #2153: Zhihu false positive
Credited to @tf7software

### PR DESCRIPTION
**Pull request by sdushantha**
- fixed freeCodeCamp false positive
- fixed LibraryThing false positive
- removed Zhihu due to false positives, closes #2153

### CODE REVIEW

**Comment by ppfeister** [comment]
As long as those fixes work, this can be merged

The failed tests can be ignored. Reading the log, the only failure is the pentestit probe that was swapped out in #2187. All other tests pass.

**Comment by sdushantha** [comment]
@ppfeister There is a merge conflict that needs to be fixed. I'll do it in the next 24 hours

**Comment by ppfeister** [comment]
I can just 3wm it locally if needed, just takes a few seconds @sdushantha

**Comment by sdushantha** [comment]
@ppfeister If you've got time, feel free to do it

**Pull request merged**
