### PR TITLE
Updated docs to inlcude poetry to requirements.txt convertion

### LINKED ISSUE #2156: Installation from sources
### Installation method

Built from source

### Description

You have removed the requirements.txt that allow installation from source !

### Steps to reproduce

Do a basic installation from sources. 

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sdushantha**
fixes #2156

### CODE REVIEW

**Comment by ppfeister** [comment]
I remember doing this locally, but I guess I forgot to push 😶

**Comment by ppfeister** [comment]
I think it would go better moved up to immediately following the "Build live package from source (useful for contributors)" header, since building from source would also require it for some workflows

Agree/disagree?

**Comment by sdushantha** [comment]
I agree, changes has been made accordingly

**Comment by sdushantha** [comment]
Closing this as its been fixed in #2160

**Comment by ppfeister** [comment]
huh... i guess i did pr it

and you even suggested changes

man, i've been _out of it_ the last few days

**Pull request closed without merging**
