### PR TITLE
Add furaffinity

### PR DESCRIPTION
**Pull request by j4asper**
Add Furaffinity to sites
#1291

### CODE REVIEW

**Comment by sdushantha** [comment]
Please fix the conflicts. I'll review the PR once you've done that 👍

**Comment by j4asper** [comment]
There you go

**Comment by sdushantha** [comment]
Seems like you only removed the site from the `removed_sites.md` and `removed_sites.json` but haven't added anything to `data.json`.

https://github.com/sherlock-project/sherlock/pull/1416/files

**Comment by j4asper** [comment]
I am a github noob, it's in there now

**Review by victomized — COMMENTED** [review]
- - Glad I could help. Let me know if y'all need anything else

**Pull request merged**
