### PR TITLE
Add Fanpop

### LINKED ISSUE #2268: Requesting support for: Fanpop
### Site URL

https://fanpop.com

### Additional info

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ntexe**
Closes #2268 

I have added Fanpop site which was removed earlier.

### CODE REVIEW

**Review by ntexe — COMMENTED** [review]
So I've made a couple of commits to make my PR pass the tests. It works
image

**Comment by ntexe** [comment]
Hi @ppfeister, PTAL :)

**Comment by ppfeister** [comment]
Good add!

Tried to squash your commits and the forge imploded. git handled it well, GitHub did not. So while GitHub is showing this PR as closed, your changes actually did get merged under the commit f7075e1. Also visible when searching for authored commits in the repo [[click]](https://github.com/sherlock-project/sherlock/commits?author=ntexe).

**Comment by ntexe** [comment]
@ppfeister Thanks :)

**Comment by Jhonatanbb** [comment]
//www.sexlog.com/vadiaquerleite

**Pull request closed without merging**
