### PR TITLE
Put the original creator to license section.

### PR DESCRIPTION
**Pull request by jcs090218**
I think putting original creator under License will be a much better place. Or at least right above `License`. What do you guys think? @sdushantha @TheYahya 

Totally just an option.

### CODE REVIEW

**Comment by sdushantha** [comment]
@jcs090218 What about having it in the README.md and the License? I dont think people are going to check the License that much.

**Comment by jcs090218** [comment]
> I dont think people are going to check the License that much.

@sdushantha Base on my habit, if I wonder who is the creator of a project, the license should always have the creators' and the maintainers' name on it. I usually go straight to the license but this is very subjective habit.

> @jcs090218 What about having it in the README.md and the License? 

Not sure what do you mean by this. README.md and License already have your name on it, does it?

And still, this is just a suggestion. :D

**Comment by sdushantha** [comment]
@jcs090218 Sorry, I miss read your PR. 
I think this PR should be merged :)

**Comment by jcs090218** [comment]
@sdushantha Cool, I think I know what you meant in the previous dialogue. Yeah, just check the `Files changed` tab, I only moved the original creator under the `license` section (not the license file).

**Comment by TheYahya** [comment]
It's a better idea 👍

**Pull request merged**
