### PR TITLE
Fix dependency conflict for issue

### PR DESCRIPTION
**Pull request by NeolithEra**
#295

### CODE REVIEW

**Comment by NeolithEra** [comment]
@sdushantha 
Could you please help me review this issue?    
Thank you very much!

BTW, dependency conflict problems are very common in practice in python ecosystem.
I have encountered the issues several times. What's your oppinion on the challenges of detecting and repairing such issues?
And how to avoid dependency conflict problems among python projects, especially from the ecosystem's perspective?

**Comment by sdushantha** [comment]
@NeolithEra 
I think it would be wise to include the version of the module as well.
For example:
```
requests >= 2.22.0 
```

**Comment by sdushantha** [comment]
@NeolithEra Could you do that with all the modules in `requirements.txt`

**Comment by sdushantha** [comment]
Thank you @NeolithEra :)

**Pull request merged**
