### PR TITLE
Fix stray f's that break on Linux

### PR DESCRIPTION
**Pull request by snehankekre**
On first cloning the original repo an running `sherlock.py` I kept getting syntax errors due to the `f` characters present on many lines. I've removed those so that it now works without breaking. 

I've also replaced all instances of "TOR" with "Tor". See: https://2019.www.torproject.org/docs/faq.html.en#WhyCalledTor 

> Note: even though it originally came from an acronym, Tor is not spelled "TOR". Only the first letter is capitalized. In fact, we can usually spot people who haven't read any of our website (and have instead learned everything they know about Tor from news articles) by the fact that they spell it wrong.

### CODE REVIEW

**Comment by hoadlck** [comment]
Other people are using Sherlock on Linux without any problems.  The f characters that you changed are how one denotes that we are using f-strings (or format strings). This is used to properly print out the results.

I suspect that the problems you were having with f characters was that you were using the wrong version of Python. Sherlock requires Python 3.6 or higher.

**Comment by TheYahya** [comment]
Tnx @snehankekre, Merged.

**Comment by hoadlck** [comment]
Why was this merged?  This PR removed format strings that were required for proper operation.  The main line is all whacked up.

**Comment by hoadlck** [comment]
I backed out this PR and pushed it to main.  I did not have time to do detailed testing, but the failures now seem to be the "normal" ones that happen because a site is slow to respond.

**Pull request closed without merging**
