### PR TITLE
updated README.md

### LINKED ISSUE #1529: update README.md
please assign this issue to me

### PR DESCRIPTION
**Pull request by itsAftabAlam**
added hyperlink to banner. fixes #1529

### CODE REVIEW

**Comment by itsAftabAlam** [comment]
please review and merge if it helped

**Review by Haterium — COMMENTED** [review]
Okay

**Review by Haterium — COMMENTED** [review]
Okay

**Review by sdushantha — APPROVED** [review]

**Comment by itsAftabAlam** [comment]
@Haterium @sdushantha  can you please add hacktoberfest-accepted label?

**Comment by sdushantha** [comment]
@itsAftabAlam sorry, forgot about that, done it now 👍

**Comment by itsAftabAlam** [comment]
@sdushantha thanks, hope to come back with some technical contribution

**Pull request merged**
