### PR TITLE
Install sherlock directory as a module

### PR DESCRIPTION
**Pull request by mjsir911**
Was previously polluting the site-packages directory with top-level python files

```
$ ls venv/lib/python3.11/site-packages/
PySocks-1.7.1.dist-info             dateutil                    openpyxl-3.1.2.dist-info               requests_futures-1.0.1.dist-info   stem
__init__.py                         distutils-precedence.pth    pandas                                 resources                          stem-1.8.2.dist-info
__main__.py                         et_xmlfile                  pandas-2.2.2.dist-info                 result.py                          tests
__pycache__                         et_xmlfile-1.1.0.dist-info  pip                                    setuptools                         torrequest-0.1.0.dist-info
_distutils_hack                     exrex-0.11.0.dist-info      pip-24.0.dist-info                     setuptools-69.5.1.dist-info        torrequest.py
_virtualenv.pth                     exrex.py                    pip-24.0.virtualenv                    setuptools-69.5.1.virtualenv       tzdata
_virtualenv.py                      idna                        pkg_resources                          sherlock.py                        tzdata-2024.1.dist-info
certifi                             idna-3.7.dist-info          python_dateutil-2.9.0.post0.dist-info  sherlock_project-0.14.4.dist-info  urllib3
certifi-2024.2.2.dist-info          notify.py                   pytz                                   sites.py                           urllib3-2.2.1.dist-info
charset_normalizer                  numpy                       pytz-2024.1.dist-info                  six-1.16.0.dist-info               wheel
charset_normalizer-3.3.2.dist-info  numpy-1.26.4.dist-info      requests                               six.py                             wheel-0.43.0.dist-info
colorama                            numpy.libs                  requests-2.32.2.dist-info              socks.py                           wheel-0.43.0.virtualenv
colorama-0.4.6.dist-info            openpyxl                    requests_futures                       sockshandler.py
```

### CODE REVIEW

**Comment by ppfeister** [comment]
Seriously? That was the fix?

I spent way too much time trying to diagnose this. After seeing it here, it seems glaringly obvious.

___

This is already going to be fixed due to the switch to Poetry in #2111. Not sure when exactly that'll be merged. Would you prefer this to be merged in the interim and repack later, or hold out for Poetry and tox?

**Comment by mjsir911** [comment]
If it's any consolation i spent way too much time with the knowledgeable packaging people here at pycon debugging the fact that if you don't clean out your working directory, pip will continue to install the old egg files found within the sherlock subdirectory.

A `git clean -fxd` fixed oddities that were showing up

May 22, 2024 3:24:59 PM Paul Pfeister ***@***.***>:

**Comment by ppfeister** [comment]
`git clean -fxd` is my # 15 most used command apparently. The egg issue always gets me.

I assume you installed with this change. Did you use `pip install .` or some other method? I seem to be experiencing import issues with this.

Seems we may need to adjust the imports now that it's installed 'properly'. We had to do something similar with Poetry.

**Comment by mjsir911** [comment]
@ppfeister does the commit you've added fix things? Not sure if we want to go through with this one or close in preference of #2147 or just wait till #2127 goes through.

**Comment by ppfeister** [comment]
Good timing on your reply @mjsir911, I had just opened this up a few hours earlier trying to remember what I had committed here

Anyways, we were able to finish testing 2127 and I just merged it in, finally implementing Poetry. Packaging issues should be fixed now!

**Pull request closed without merging**
