### PR TITLE
Added Support for Quora

### PR DESCRIPTION
**Pull request by shekhuverma**
Added back the support for quora.

### CODE REVIEW

**Comment by mrsofiane** [comment]
Not working for me
Screenshot 2022-10-19 at 19 07 50

**Comment by P3nt3st3r123** [comment]
@mrsofiane! Try this
```
"Quora": {
    "errorType": "status_code",
    "request_method": "GET",
    "url": "https://www.quora.com/profile/{}",
    "urlMain": "https://www.quora.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis"
  },
```

**Comment by P3nt3st3r123** [comment]
Because request method HEAD in quora has been blocked by cloudflare

**Comment by mrsofiane** [comment]
@P3nt3st3r123 Yes thats what i did in #1570, it was blocked by cloudflare.

**Comment by sdushantha** [comment]
There is an issue Quora where it redirects to `/topics/username` which will return false postives

**Pull request closed without merging**
