### PR TITLE
Added LinkedIn.com

### PR DESCRIPTION
**Pull request by Alexandros-Kordatzakis**
Fully tested and Working!

As per @hoadlck request.

### CODE REVIEW

**Comment by hoadlck** [comment]
I merged this, but the tests to not pass.  

Here are just a couple of commands that I ran to illustrate the issue:
```
% python -u sherlock.py --site LinkedIn alex

[*] Checking username alex on:
[+] LinkedIn: https://www.linkedin.com/in/alex
% python -u sherlock.py --site LinkedIn noonewouldeverusethis7

[*] Checking username noonewouldeverusethis7 on:
[+] LinkedIn: https://www.linkedin.com/in/noonewouldeverusethis7
```
Do you have a LinkedIn account?  It seems like things like this have happened to others: it works for them because they are logged in on their computer.  But, it does not work for others.

**Comment by hoadlck** [comment]
Marking this as "do not merge" until it passes tests.

**Comment by Alexandros-Kordatzakis** [comment]
Well, LinkedIn.com requires an account to see others accounts.

Other than that, I tried what you said. It is possible. I tried to edit this with Incognito Mode URL's (no passwords or accounts logged in) and it will never work. If you don't have a LinkedIn account, your result will always be their page to create an account. 

To conclude, there is no point in adding this site, as the script [Sherlock] doesn't have a LinkedIn account to check the availability. Unless LinkedIn.com doesn't change the way they search for People-Accounts, this is not possible. (At least to my knowledge.)

Thank you and sorry.

**Comment by hoadlck** [comment]
Ah...that is a bummer.  I added a note in the [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md) file, so we will remember this for the future.

**Pull request closed without merging**
