### PR TITLE
Add code.golf

### PR DESCRIPTION
**Pull request by cloud11665**

### CODE REVIEW

**Comment by Cloud11665** [comment]
sooooo, is this getting merged, @sdushantha ?

**Comment by sdushantha** [comment]
@Cloud11665 I am currently very busy and do not have much time to review the code. Sherlock currently has a lot of false positives, therefore I have to prioritize fixing false positives when I do get some time to work on Sherlock.

**Review by RealFinalCode — CHANGES_REQUESTED** [review]
Please add CodeGolf to the sites.md file.

**Comment by Cloud11665** [comment]
@RealFinalCode done

**Review by RealFinalCode — APPROVED** [review]
Looks good no false/positives.

**Comment by Cloud11665** [comment]
?

**Pull request closed without merging**
