### PR TITLE
Deprecate Python 3.8

### LINKED ISSUE #2266: Deprecate support for Python 3.8
### Description

Some versions of pandas and numpy are incompatible, and the compatible versions of pandas is not compatible with Python versions below 3.9. Since Python 3.8 is reaching EOL in about a month anyways, support for this version should now be deprecated to allow for more ready dependency resolution and avoidance of this fatal error.

```
Traceback (most recent call last):
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/bin/sherlock", line 3, in <module>
    from sherlock_project.sherlock import main
  File "/home/[redacted]/Documents/sherlock/sherlock_project/sherlock.py", line 21, in <module>
    import pandas as pd
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/[redacted]/.cache/pypoetry/virtualenvs/sherlock-project-VJORHILj-py3.12/lib64/python3.12/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### PR DESCRIPTION
**Pull request by ppfeister**
Python 3.8 is nearing EOL, and it's being deprecated here to allow for more ready dependency resolution between pandas and numpy, avoiding a fatal import.

fc39 will be EOL November 12, 2024, and most users should have upgraded to fc40 by now, so I don't see much reason to continue support for that either.

Closes #2266

### CODE REVIEW

**Comment by ppfeister** [comment]
Now that fc39 and 3.8 are finally EOL, I don't see any reason to keep withholding a merge. Any opposition to said merge? @sdushantha 

Simple deprecation of 3.8. Should have no functional difference, although the pandas issue may also become less prevalent (as a positive side effect).

**Review by matheusfelipeog — APPROVED** [review]
Nothing against it at the moment. Sounds good.

**Review by sdushantha — APPROVED** [review]

**Comment by sdushantha** [comment]
LGTM

**Comment by fatimathekhan66-debug** [comment]
how to use github i mistakenly login w my google account !!

**Review by mkkrahmer — APPROVED** [review]

**Pull request merged**
